# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'server_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_server(object):
    def setupUi(self, server):
        server.setObjectName("server")
        server.resize(436, 383)
        self.centralwidget = QtWidgets.QWidget(server)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.checkBoxEcho = QtWidgets.QCheckBox(self.frame)
        self.checkBoxEcho.setText("")
        self.checkBoxEcho.setObjectName("checkBoxEcho")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.checkBoxEcho)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEditMsg = QtWidgets.QLineEdit(self.frame_3)
        self.lineEditMsg.setObjectName("lineEditMsg")
        self.horizontalLayout_2.addWidget(self.lineEditMsg)
        self.buttonSend = QtWidgets.QPushButton(self.frame_3)
        self.buttonSend.setObjectName("buttonSend")
        self.horizontalLayout_2.addWidget(self.buttonSend)
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.frame_3)
        self.textBrowser = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser.setObjectName("textBrowser")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.textBrowser)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spinBoxPort = QtWidgets.QSpinBox(self.frame_2)
        self.spinBoxPort.setMinimum(1001)
        self.spinBoxPort.setMaximum(10000)
        self.spinBoxPort.setProperty("value", 1002)
        self.spinBoxPort.setObjectName("spinBoxPort")
        self.horizontalLayout.addWidget(self.spinBoxPort)
        self.buttonStartStop = QtWidgets.QPushButton(self.frame_2)
        self.buttonStartStop.setObjectName("buttonStartStop")
        self.horizontalLayout.addWidget(self.buttonStartStop)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.frame_2)
        self.verticalLayout.addWidget(self.frame)
        server.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(server)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 436, 26))
        self.menubar.setObjectName("menubar")
        server.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(server)
        self.statusbar.setObjectName("statusbar")
        server.setStatusBar(self.statusbar)

        self.retranslateUi(server)
        QtCore.QMetaObject.connectSlotsByName(server)

    def retranslateUi(self, server):
        _translate = QtCore.QCoreApplication.translate
        server.setWindowTitle(_translate("server", "I\'m the Server"))
        self.label_2.setText(_translate("server", "echo "))
        self.label.setText(_translate("server", "port "))
        self.label_3.setText(_translate("server", "respond"))
        self.label_4.setText(_translate("server", "log"))
        self.lineEditMsg.setText(_translate("server", "hello client"))
        self.buttonSend.setToolTip(_translate("server", "<html><head/><body><p>the GUI will freeze while computing in main thread</p></body></html>"))
        self.buttonSend.setText(_translate("server", "send"))
        self.buttonStartStop.setText(_translate("server", "start stop"))

